// Code generated by protoc-gen-go. DO NOT EDIT.
// source: zsys.proto

package zsys

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_05865bfaed6eea5d, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type LogResponse struct {
	Log                  string   `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogResponse) Reset()         { *m = LogResponse{} }
func (m *LogResponse) String() string { return proto.CompactTextString(m) }
func (*LogResponse) ProtoMessage()    {}
func (*LogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_05865bfaed6eea5d, []int{1}
}

func (m *LogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogResponse.Unmarshal(m, b)
}
func (m *LogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogResponse.Marshal(b, m, deterministic)
}
func (m *LogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogResponse.Merge(m, src)
}
func (m *LogResponse) XXX_Size() int {
	return xxx_messageInfo_LogResponse.Size(m)
}
func (m *LogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogResponse proto.InternalMessageInfo

func (m *LogResponse) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

type VersionResponse struct {
	// Types that are valid to be assigned to Reply:
	//	*VersionResponse_Log
	//	*VersionResponse_Version
	Reply                isVersionResponse_Reply `protobuf_oneof:"reply"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_05865bfaed6eea5d, []int{2}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

type isVersionResponse_Reply interface {
	isVersionResponse_Reply()
}

type VersionResponse_Log struct {
	Log string `protobuf:"bytes,1,opt,name=log,proto3,oneof"`
}

type VersionResponse_Version struct {
	Version string `protobuf:"bytes,2,opt,name=version,proto3,oneof"`
}

func (*VersionResponse_Log) isVersionResponse_Reply() {}

func (*VersionResponse_Version) isVersionResponse_Reply() {}

func (m *VersionResponse) GetReply() isVersionResponse_Reply {
	if m != nil {
		return m.Reply
	}
	return nil
}

func (m *VersionResponse) GetLog() string {
	if x, ok := m.GetReply().(*VersionResponse_Log); ok {
		return x.Log
	}
	return ""
}

func (m *VersionResponse) GetVersion() string {
	if x, ok := m.GetReply().(*VersionResponse_Version); ok {
		return x.Version
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*VersionResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*VersionResponse_Log)(nil),
		(*VersionResponse_Version)(nil),
	}
}

type CreateUserDataRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Homepath             string   `protobuf:"bytes,2,opt,name=homepath,proto3" json:"homepath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserDataRequest) Reset()         { *m = CreateUserDataRequest{} }
func (m *CreateUserDataRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserDataRequest) ProtoMessage()    {}
func (*CreateUserDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_05865bfaed6eea5d, []int{3}
}

func (m *CreateUserDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserDataRequest.Unmarshal(m, b)
}
func (m *CreateUserDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserDataRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserDataRequest.Merge(m, src)
}
func (m *CreateUserDataRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserDataRequest.Size(m)
}
func (m *CreateUserDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserDataRequest proto.InternalMessageInfo

func (m *CreateUserDataRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *CreateUserDataRequest) GetHomepath() string {
	if m != nil {
		return m.Homepath
	}
	return ""
}

type ChangeHomeOnUserDataRequest struct {
	Home                 string   `protobuf:"bytes,1,opt,name=home,proto3" json:"home,omitempty"`
	NewHome              string   `protobuf:"bytes,2,opt,name=newHome,proto3" json:"newHome,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeHomeOnUserDataRequest) Reset()         { *m = ChangeHomeOnUserDataRequest{} }
func (m *ChangeHomeOnUserDataRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeHomeOnUserDataRequest) ProtoMessage()    {}
func (*ChangeHomeOnUserDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_05865bfaed6eea5d, []int{4}
}

func (m *ChangeHomeOnUserDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeHomeOnUserDataRequest.Unmarshal(m, b)
}
func (m *ChangeHomeOnUserDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeHomeOnUserDataRequest.Marshal(b, m, deterministic)
}
func (m *ChangeHomeOnUserDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeHomeOnUserDataRequest.Merge(m, src)
}
func (m *ChangeHomeOnUserDataRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeHomeOnUserDataRequest.Size(m)
}
func (m *ChangeHomeOnUserDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeHomeOnUserDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeHomeOnUserDataRequest proto.InternalMessageInfo

func (m *ChangeHomeOnUserDataRequest) GetHome() string {
	if m != nil {
		return m.Home
	}
	return ""
}

func (m *ChangeHomeOnUserDataRequest) GetNewHome() string {
	if m != nil {
		return m.NewHome
	}
	return ""
}

type PrepareBootResponse struct {
	// Types that are valid to be assigned to Reply:
	//	*PrepareBootResponse_Log
	//	*PrepareBootResponse_Changed
	Reply                isPrepareBootResponse_Reply `protobuf_oneof:"reply"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *PrepareBootResponse) Reset()         { *m = PrepareBootResponse{} }
func (m *PrepareBootResponse) String() string { return proto.CompactTextString(m) }
func (*PrepareBootResponse) ProtoMessage()    {}
func (*PrepareBootResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_05865bfaed6eea5d, []int{5}
}

func (m *PrepareBootResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareBootResponse.Unmarshal(m, b)
}
func (m *PrepareBootResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareBootResponse.Marshal(b, m, deterministic)
}
func (m *PrepareBootResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareBootResponse.Merge(m, src)
}
func (m *PrepareBootResponse) XXX_Size() int {
	return xxx_messageInfo_PrepareBootResponse.Size(m)
}
func (m *PrepareBootResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareBootResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareBootResponse proto.InternalMessageInfo

type isPrepareBootResponse_Reply interface {
	isPrepareBootResponse_Reply()
}

type PrepareBootResponse_Log struct {
	Log string `protobuf:"bytes,1,opt,name=log,proto3,oneof"`
}

type PrepareBootResponse_Changed struct {
	Changed bool `protobuf:"varint,2,opt,name=changed,proto3,oneof"`
}

func (*PrepareBootResponse_Log) isPrepareBootResponse_Reply() {}

func (*PrepareBootResponse_Changed) isPrepareBootResponse_Reply() {}

func (m *PrepareBootResponse) GetReply() isPrepareBootResponse_Reply {
	if m != nil {
		return m.Reply
	}
	return nil
}

func (m *PrepareBootResponse) GetLog() string {
	if x, ok := m.GetReply().(*PrepareBootResponse_Log); ok {
		return x.Log
	}
	return ""
}

func (m *PrepareBootResponse) GetChanged() bool {
	if x, ok := m.GetReply().(*PrepareBootResponse_Changed); ok {
		return x.Changed
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PrepareBootResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PrepareBootResponse_Log)(nil),
		(*PrepareBootResponse_Changed)(nil),
	}
}

type CommitBootResponse struct {
	// Types that are valid to be assigned to Reply:
	//	*CommitBootResponse_Log
	//	*CommitBootResponse_Changed
	Reply                isCommitBootResponse_Reply `protobuf_oneof:"reply"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CommitBootResponse) Reset()         { *m = CommitBootResponse{} }
func (m *CommitBootResponse) String() string { return proto.CompactTextString(m) }
func (*CommitBootResponse) ProtoMessage()    {}
func (*CommitBootResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_05865bfaed6eea5d, []int{6}
}

func (m *CommitBootResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitBootResponse.Unmarshal(m, b)
}
func (m *CommitBootResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitBootResponse.Marshal(b, m, deterministic)
}
func (m *CommitBootResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitBootResponse.Merge(m, src)
}
func (m *CommitBootResponse) XXX_Size() int {
	return xxx_messageInfo_CommitBootResponse.Size(m)
}
func (m *CommitBootResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitBootResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommitBootResponse proto.InternalMessageInfo

type isCommitBootResponse_Reply interface {
	isCommitBootResponse_Reply()
}

type CommitBootResponse_Log struct {
	Log string `protobuf:"bytes,1,opt,name=log,proto3,oneof"`
}

type CommitBootResponse_Changed struct {
	Changed bool `protobuf:"varint,2,opt,name=changed,proto3,oneof"`
}

func (*CommitBootResponse_Log) isCommitBootResponse_Reply() {}

func (*CommitBootResponse_Changed) isCommitBootResponse_Reply() {}

func (m *CommitBootResponse) GetReply() isCommitBootResponse_Reply {
	if m != nil {
		return m.Reply
	}
	return nil
}

func (m *CommitBootResponse) GetLog() string {
	if x, ok := m.GetReply().(*CommitBootResponse_Log); ok {
		return x.Log
	}
	return ""
}

func (m *CommitBootResponse) GetChanged() bool {
	if x, ok := m.GetReply().(*CommitBootResponse_Changed); ok {
		return x.Changed
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CommitBootResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CommitBootResponse_Log)(nil),
		(*CommitBootResponse_Changed)(nil),
	}
}

func init() {
	proto.RegisterType((*Empty)(nil), "zsys.Empty")
	proto.RegisterType((*LogResponse)(nil), "zsys.LogResponse")
	proto.RegisterType((*VersionResponse)(nil), "zsys.VersionResponse")
	proto.RegisterType((*CreateUserDataRequest)(nil), "zsys.CreateUserDataRequest")
	proto.RegisterType((*ChangeHomeOnUserDataRequest)(nil), "zsys.ChangeHomeOnUserDataRequest")
	proto.RegisterType((*PrepareBootResponse)(nil), "zsys.PrepareBootResponse")
	proto.RegisterType((*CommitBootResponse)(nil), "zsys.CommitBootResponse")
}

func init() { proto.RegisterFile("zsys.proto", fileDescriptor_05865bfaed6eea5d) }

var fileDescriptor_05865bfaed6eea5d = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xcb, 0x4f, 0xc2, 0x40,
	0x10, 0xc6, 0x2d, 0x82, 0xc5, 0x21, 0xf1, 0x31, 0x4a, 0x52, 0xcb, 0x41, 0xed, 0xc9, 0x13, 0x36,
	0x1a, 0xe3, 0x1d, 0x34, 0x12, 0x1f, 0x68, 0x9a, 0xe8, 0xc1, 0x5b, 0xd5, 0x09, 0x90, 0xd0, 0x6e,
	0xdd, 0x5d, 0x34, 0xf5, 0x5f, 0xf3, 0x9f, 0x33, 0xfb, 0xe0, 0x51, 0xad, 0xf1, 0xe2, 0x6d, 0x66,
	0xfa, 0xf5, 0xb7, 0x3b, 0xdf, 0xb7, 0x00, 0x1f, 0x22, 0x17, 0xed, 0x8c, 0x33, 0xc9, 0xb0, 0xaa,
	0xea, 0xc0, 0x85, 0xda, 0x79, 0x92, 0xc9, 0x3c, 0xd8, 0x85, 0xc6, 0x35, 0x1b, 0x44, 0x24, 0x32,
	0x96, 0x0a, 0xc2, 0x0d, 0x58, 0x1e, 0xb3, 0x81, 0xe7, 0xec, 0x39, 0x07, 0xab, 0x91, 0x2a, 0x83,
	0x4b, 0x58, 0x7f, 0x20, 0x2e, 0x46, 0x2c, 0x9d, 0x89, 0x70, 0x41, 0xd4, 0x5b, 0xd2, 0x32, 0xf4,
	0xc1, 0x7d, 0x33, 0x32, 0xaf, 0x62, 0xe7, 0xd3, 0x41, 0xc7, 0x85, 0x1a, 0xa7, 0x6c, 0x9c, 0x07,
	0x17, 0xd0, 0xec, 0x72, 0x8a, 0x25, 0xdd, 0x0b, 0xe2, 0x67, 0xb1, 0x8c, 0x23, 0x7a, 0x9d, 0x90,
	0x90, 0x88, 0x50, 0x9d, 0x08, 0xe2, 0xf6, 0x5c, 0x5d, 0xa3, 0x0f, 0xf5, 0x21, 0x4b, 0x28, 0x8b,
	0xe5, 0xd0, 0x20, 0xa3, 0x59, 0x1f, 0x5c, 0x41, 0xab, 0x3b, 0x8c, 0xd3, 0x01, 0xf5, 0x58, 0x42,
	0xb7, 0x69, 0x09, 0x4e, 0x49, 0xa7, 0x38, 0x55, 0xa3, 0x07, 0x6e, 0x4a, 0xef, 0x4a, 0x6f, 0x69,
	0xd3, 0x36, 0xe8, 0xc3, 0xd6, 0x1d, 0xa7, 0x2c, 0xe6, 0xd4, 0x61, 0x4c, 0xfe, 0xb5, 0xe5, 0xb3,
	0x3e, 0xf7, 0x45, 0x43, 0xea, 0x6a, 0x4b, 0x3b, 0x98, 0x6f, 0x79, 0x03, 0xd8, 0x65, 0x49, 0x32,
	0x92, 0xff, 0x82, 0x3b, 0xfa, 0xac, 0x40, 0xf5, 0x51, 0xe4, 0x02, 0x0f, 0xc1, 0xb5, 0x49, 0x60,
	0xa3, 0xad, 0x13, 0xd5, 0x11, 0xfa, 0x4d, 0xd3, 0x7c, 0x4b, 0x29, 0x74, 0xb0, 0x03, 0x6b, 0x45,
	0xbb, 0xb1, 0x65, 0xa4, 0xa5, 0x21, 0xf8, 0x9b, 0xe6, 0xe3, 0xc2, 0x73, 0x08, 0x1d, 0xec, 0xc3,
	0x76, 0x99, 0xd3, 0xb8, 0x6f, 0x49, 0xbf, 0xa7, 0x50, 0xce, 0x3b, 0x85, 0xc6, 0x82, 0xd9, 0xc5,
	0x45, 0x76, 0x4c, 0x53, 0x12, 0x46, 0xe8, 0xe0, 0x09, 0xc0, 0xdc, 0xd5, 0xe2, 0x7f, 0x9e, 0xbd,
	0xcb, 0x0f, 0xd3, 0x43, 0xe7, 0x69, 0x45, 0xbf, 0xfa, 0xe3, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x4d, 0x63, 0x94, 0x5d, 0x03, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ZsysClient is the client API for Zsys service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ZsysClient interface {
	Version(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Zsys_VersionClient, error)
	CreateUserData(ctx context.Context, in *CreateUserDataRequest, opts ...grpc.CallOption) (Zsys_CreateUserDataClient, error)
	ChangeHomeOnUserData(ctx context.Context, in *ChangeHomeOnUserDataRequest, opts ...grpc.CallOption) (Zsys_ChangeHomeOnUserDataClient, error)
	PrepareBoot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Zsys_PrepareBootClient, error)
	CommitBoot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Zsys_CommitBootClient, error)
}

type zsysClient struct {
	cc *grpc.ClientConn
}

func NewZsysClient(cc *grpc.ClientConn) ZsysClient {
	return &zsysClient{cc}
}

func (c *zsysClient) Version(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Zsys_VersionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Zsys_serviceDesc.Streams[0], "/zsys.Zsys/Version", opts...)
	if err != nil {
		return nil, err
	}
	x := &zsysVersionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Zsys_VersionClient interface {
	Recv() (*VersionResponse, error)
	grpc.ClientStream
}

type zsysVersionClient struct {
	grpc.ClientStream
}

func (x *zsysVersionClient) Recv() (*VersionResponse, error) {
	m := new(VersionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *zsysClient) CreateUserData(ctx context.Context, in *CreateUserDataRequest, opts ...grpc.CallOption) (Zsys_CreateUserDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Zsys_serviceDesc.Streams[1], "/zsys.Zsys/CreateUserData", opts...)
	if err != nil {
		return nil, err
	}
	x := &zsysCreateUserDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Zsys_CreateUserDataClient interface {
	Recv() (*LogResponse, error)
	grpc.ClientStream
}

type zsysCreateUserDataClient struct {
	grpc.ClientStream
}

func (x *zsysCreateUserDataClient) Recv() (*LogResponse, error) {
	m := new(LogResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *zsysClient) ChangeHomeOnUserData(ctx context.Context, in *ChangeHomeOnUserDataRequest, opts ...grpc.CallOption) (Zsys_ChangeHomeOnUserDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Zsys_serviceDesc.Streams[2], "/zsys.Zsys/ChangeHomeOnUserData", opts...)
	if err != nil {
		return nil, err
	}
	x := &zsysChangeHomeOnUserDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Zsys_ChangeHomeOnUserDataClient interface {
	Recv() (*LogResponse, error)
	grpc.ClientStream
}

type zsysChangeHomeOnUserDataClient struct {
	grpc.ClientStream
}

func (x *zsysChangeHomeOnUserDataClient) Recv() (*LogResponse, error) {
	m := new(LogResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *zsysClient) PrepareBoot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Zsys_PrepareBootClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Zsys_serviceDesc.Streams[3], "/zsys.Zsys/PrepareBoot", opts...)
	if err != nil {
		return nil, err
	}
	x := &zsysPrepareBootClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Zsys_PrepareBootClient interface {
	Recv() (*PrepareBootResponse, error)
	grpc.ClientStream
}

type zsysPrepareBootClient struct {
	grpc.ClientStream
}

func (x *zsysPrepareBootClient) Recv() (*PrepareBootResponse, error) {
	m := new(PrepareBootResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *zsysClient) CommitBoot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Zsys_CommitBootClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Zsys_serviceDesc.Streams[4], "/zsys.Zsys/CommitBoot", opts...)
	if err != nil {
		return nil, err
	}
	x := &zsysCommitBootClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Zsys_CommitBootClient interface {
	Recv() (*CommitBootResponse, error)
	grpc.ClientStream
}

type zsysCommitBootClient struct {
	grpc.ClientStream
}

func (x *zsysCommitBootClient) Recv() (*CommitBootResponse, error) {
	m := new(CommitBootResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ZsysServer is the server API for Zsys service.
type ZsysServer interface {
	Version(*Empty, Zsys_VersionServer) error
	CreateUserData(*CreateUserDataRequest, Zsys_CreateUserDataServer) error
	ChangeHomeOnUserData(*ChangeHomeOnUserDataRequest, Zsys_ChangeHomeOnUserDataServer) error
	PrepareBoot(*Empty, Zsys_PrepareBootServer) error
	CommitBoot(*Empty, Zsys_CommitBootServer) error
}

// UnimplementedZsysServer can be embedded to have forward compatible implementations.
type UnimplementedZsysServer struct {
}

func (*UnimplementedZsysServer) Version(req *Empty, srv Zsys_VersionServer) error {
	return status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (*UnimplementedZsysServer) CreateUserData(req *CreateUserDataRequest, srv Zsys_CreateUserDataServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateUserData not implemented")
}
func (*UnimplementedZsysServer) ChangeHomeOnUserData(req *ChangeHomeOnUserDataRequest, srv Zsys_ChangeHomeOnUserDataServer) error {
	return status.Errorf(codes.Unimplemented, "method ChangeHomeOnUserData not implemented")
}
func (*UnimplementedZsysServer) PrepareBoot(req *Empty, srv Zsys_PrepareBootServer) error {
	return status.Errorf(codes.Unimplemented, "method PrepareBoot not implemented")
}
func (*UnimplementedZsysServer) CommitBoot(req *Empty, srv Zsys_CommitBootServer) error {
	return status.Errorf(codes.Unimplemented, "method CommitBoot not implemented")
}

func RegisterZsysServer(s *grpc.Server, srv ZsysServer) {
	s.RegisterService(&_Zsys_serviceDesc, srv)
}

func _Zsys_Version_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ZsysServer).Version(m, &zsysVersionServer{stream})
}

type Zsys_VersionServer interface {
	Send(*VersionResponse) error
	grpc.ServerStream
}

type zsysVersionServer struct {
	grpc.ServerStream
}

func (x *zsysVersionServer) Send(m *VersionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Zsys_CreateUserData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateUserDataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ZsysServer).CreateUserData(m, &zsysCreateUserDataServer{stream})
}

type Zsys_CreateUserDataServer interface {
	Send(*LogResponse) error
	grpc.ServerStream
}

type zsysCreateUserDataServer struct {
	grpc.ServerStream
}

func (x *zsysCreateUserDataServer) Send(m *LogResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Zsys_ChangeHomeOnUserData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChangeHomeOnUserDataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ZsysServer).ChangeHomeOnUserData(m, &zsysChangeHomeOnUserDataServer{stream})
}

type Zsys_ChangeHomeOnUserDataServer interface {
	Send(*LogResponse) error
	grpc.ServerStream
}

type zsysChangeHomeOnUserDataServer struct {
	grpc.ServerStream
}

func (x *zsysChangeHomeOnUserDataServer) Send(m *LogResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Zsys_PrepareBoot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ZsysServer).PrepareBoot(m, &zsysPrepareBootServer{stream})
}

type Zsys_PrepareBootServer interface {
	Send(*PrepareBootResponse) error
	grpc.ServerStream
}

type zsysPrepareBootServer struct {
	grpc.ServerStream
}

func (x *zsysPrepareBootServer) Send(m *PrepareBootResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Zsys_CommitBoot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ZsysServer).CommitBoot(m, &zsysCommitBootServer{stream})
}

type Zsys_CommitBootServer interface {
	Send(*CommitBootResponse) error
	grpc.ServerStream
}

type zsysCommitBootServer struct {
	grpc.ServerStream
}

func (x *zsysCommitBootServer) Send(m *CommitBootResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Zsys_serviceDesc = grpc.ServiceDesc{
	ServiceName: "zsys.Zsys",
	HandlerType: (*ZsysServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Version",
			Handler:       _Zsys_Version_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CreateUserData",
			Handler:       _Zsys_CreateUserData_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ChangeHomeOnUserData",
			Handler:       _Zsys_ChangeHomeOnUserData_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PrepareBoot",
			Handler:       _Zsys_PrepareBoot_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CommitBoot",
			Handler:       _Zsys_CommitBoot_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "zsys.proto",
}
